### ISSUE TITLE
user_data cloud-init script in docs/examples/networking/nat/ fails to run

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-provider-oci#320]
### Terraform Version

Terraform v0.10.7

### OCI Provider Version

2017/10/19 11:03:24 [INFO] terraform-provider-oci v2.0.2

### Description:

The user_data cloud-init script `user_data.tpl` in the NAT example `docs/examples/networking/nat/` is failing to run on the NatInstance, which leads to the private instance not being able connect to the Internet (i.e. it breaks the example completely).

In the `/var/log/cloud-init.log` file on NatInstance, I see the following WARNING message:

```
__init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '#\n# Create file to be us...'
```

Since the cloud-init failed to run, the `/etc/sysctl.d/98-ip-forward.conf` file does not exist and the various firewall commands specified in `user_data.tpl` also did not run.

```
[opc@NatInstance ~]$ cat /proc/sys/net/ipv4/ip_forward
0
```

```
[opc@PrivateInstance ~]$ ping -c 10 oracle.com
PING oracle.com (137.254.120.50) 56(84) bytes of data.

--- oracle.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 8999ms
```

I am not sure what about the YAML cloud-init doesn't like, but here's what it looks like from the instance:

```
[root@NatInstance log]# curl -L http://169.254.169.254/opc/v1/instance/metadata/user_data | base64 -d 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   744  100   744    0     0   745k      0 --:--:-- --:--:-- --:--:--  726k
#
# Create file to be used when enabling ip forwarding
#
write_files:
  - path: /etc/sysctl.d/98-ip-forward.conf
    content: |
      net.ipv4.ip_forward = 1

#
# Run firewall commands to enable masquerading and port forwarding
# Enable ip forwarding by setting sysctl kernel parameter
#
runcmd:
  - firewall-offline-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -o ens3 -j MASQUERADE
  - firewall-offline-cmd --direct --add-rule ipv4 filter FORWARD 0 -i ens3 -j ACCEPT
  - /bin/systemctl restart firewalld
  - sysctl -p /etc/sysctl.d/98-ip-forward.conf
```
